#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.5
# from Racc grammer file "".
#

require 'racc/parser.rb'
class IdlParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    33,   196,   108,   108,   -25,   -25,   213,   225,    60,   193,
   194,    33,   221,   222,   248,   248,   210,   212,   214,    60,
   162,    31,    35,    39,    43,    45,    46,    48,    50,    53,
    57,    73,    77,    82,    85,   127,    33,   221,   222,    33,
    20,   100,    26,    29,    60,   120,   120,    60,   210,   212,
   214,    33,    99,   193,   194,    81,    33,    31,    35,    39,
    43,    45,    46,    48,    50,    53,    57,    73,    77,   110,
   111,   112,    33,   221,   222,   108,    33,   135,    26,    29,
    60,    33,   152,   137,   138,    33,    71,    70,   145,    69,
   147,    81,    67,    31,    35,    39,    43,    45,    46,    48,
    50,    53,    57,    73,    77,    82,    85,   155,    33,    33,
    33,   115,    20,   100,    26,    29,    60,   116,   162,    33,
    65,    33,   174,   175,    99,    33,   125,    81,   108,    31,
    35,    39,    43,    45,    46,    48,    50,    53,    57,    73,
    77,    33,   185,    33,    33,   187,    33,   190,   191,   192,
    26,    29,    60,   124,   195,    33,   108,   197,   198,    33,
   201,   208,   116,    81,   216,    31,    35,    39,    43,    45,
    46,    48,    50,    53,    57,    73,    77,    82,    85,   191,
    33,   192,   115,   218,    20,   100,    26,    29,    60,   114,
    33,    33,   228,   230,    61,   113,    99,   236,   237,    81,
    33,    31,    35,    39,    43,    45,    46,    48,    50,    53,
    57,    73,    77,    82,    85,   108,    33,   240,    33,   107,
    20,   100,    26,    29,    60,   243,   244,    33,   246,   225,
   106,   250,    99,    33,   252,    81,   103,    31,    35,    39,
    43,    45,    46,    48,    50,    53,    57,    73,    77,    82,
    85,   nil,    33,   nil,   nil,   nil,    20,   100,    26,    29,
    60,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    99,   nil,
   nil,    81,   nil,    31,    35,    39,    43,    45,    46,    48,
    50,    53,    57,    73,    77,    82,    85,   nil,    33,   nil,
   nil,   nil,    20,   100,    26,    29,    60,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    99,   nil,   nil,    81,   nil,    31,
    35,    39,    43,    45,    46,    48,    50,    53,    57,    11,
   nil,   nil,   nil,    17,    22,   nil,     1,   nil,   nil,   nil,
    26,    29,   nil,   nil,   nil,    21,    24,   nil,    11,   nil,
    56,   -18,    17,    22,   nil,     1,   nil,   nil,   nil,   nil,
     5,     7,   nil,   nil,    21,    24,   nil,    20,   nil,   nil,
   nil,     4,   nil,   nil,   nil,   nil,   nil,   nil,    11,     5,
     7,   -18,    17,    22,   nil,     1,    20,   nil,   nil,   nil,
     4,   nil,   nil,   nil,    21,    24,    11,   nil,   nil,   -18,
    17,    22,   nil,     1,   nil,   nil,    33,   nil,   nil,     5,
     7,   nil,    21,    24,    60,   nil,    20,   nil,   nil,   nil,
     4,   nil,   nil,   nil,   nil,   nil,   nil,     5,     7,   178,
    43,    45,    46,    48,    20,    53,   nil,   nil,     4,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    20 ]

racc_action_check = [
    21,   173,   242,   251,   118,    65,   198,   209,    21,   204,
   204,   228,   208,   208,   242,   251,   198,   198,   198,   228,
   173,    21,    21,    21,    21,    21,    21,    21,    21,    21,
    21,    21,    21,    21,    21,    72,   121,   224,   224,   248,
    21,    21,    21,    21,   121,   118,    65,   248,   225,   225,
   225,    82,    21,   167,   167,    21,    85,   121,   121,   121,
   121,   121,   121,   121,   121,   121,   121,   121,   121,    46,
    46,    46,   219,   220,   220,    89,    93,    99,   121,   121,
   219,   100,   121,   108,   109,   113,    19,    18,   116,    16,
   119,   121,    12,   219,   219,   219,   219,   219,   219,   219,
   219,   219,   219,   219,   219,   219,   219,   122,   211,    11,
   127,   128,   219,   219,   219,   219,   211,   129,   134,   137,
    10,   141,   142,   143,   219,     7,    67,   219,   151,   211,
   211,   211,   211,   211,   211,   211,   211,   211,   211,   211,
   211,   153,   156,     5,   115,   161,   162,   163,   165,   166,
   211,   211,   115,    66,   169,    20,   179,   182,   184,   187,
   188,   197,    64,   211,   199,   115,   115,   115,   115,   115,
   115,   115,   115,   115,   115,   115,   115,   115,   115,   202,
   144,   203,    63,   207,   115,   115,   115,   115,   144,    62,
    70,     4,   216,   217,     2,    60,   115,   222,   223,   115,
    44,   144,   144,   144,   144,   144,   144,   144,   144,   144,
   144,   144,   144,   144,   144,    41,   140,   226,   227,    39,
   144,   144,   144,   144,   140,   230,   232,   233,   235,   239,
    25,   243,   144,    24,   249,   144,    23,   140,   140,   140,
   140,   140,   140,   140,   140,   140,   140,   140,   140,   140,
   140,   nil,   114,   nil,   nil,   nil,   140,   140,   140,   140,
   114,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   140,   nil,
   nil,   140,   nil,   114,   114,   114,   114,   114,   114,   114,
   114,   114,   114,   114,   114,   114,   114,   nil,     1,   nil,
   nil,   nil,   114,   114,   114,   114,     1,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   114,   nil,   nil,   114,   nil,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,   124,
   nil,   nil,   nil,   124,   124,   nil,   124,   nil,   nil,   nil,
     1,     1,   nil,   nil,   nil,   124,   124,   nil,     0,   nil,
     1,     0,     0,     0,   nil,     0,   nil,   nil,   nil,   nil,
   124,   124,   nil,   nil,     0,     0,   nil,   124,   nil,   nil,
   nil,   124,   nil,   nil,   nil,   nil,   nil,   nil,    15,     0,
     0,    15,    15,    15,   nil,    15,     0,   nil,   nil,   nil,
     0,   nil,   nil,   nil,    15,    15,   157,   nil,   nil,   157,
   157,   157,   nil,   157,   nil,   nil,   145,   nil,   nil,    15,
    15,   nil,   157,   157,   145,   nil,    15,   nil,   nil,   nil,
    15,   nil,   nil,   nil,   nil,   nil,   nil,   157,   157,   145,
   145,   145,   145,   145,   157,   145,   nil,   nil,   157,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   145 ]

racc_action_pointer = [
   334,   286,   191,   nil,   189,   141,   nil,   123,   nil,   nil,
   115,   107,    92,   nil,   nil,   364,    86,   nil,    80,    83,
   153,    -2,   nil,   233,   231,   227,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   195,
   nil,   205,   nil,   nil,   198,   nil,    44,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   185,   nil,   184,   177,   125,    -1,   148,   126,   nil,   nil,
   188,   nil,    30,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    49,   nil,   nil,    54,   nil,   nil,   nil,    65,
   nil,   nil,   nil,    74,   nil,   nil,   nil,   nil,   nil,    22,
    79,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    73,    72,
   nil,   nil,   nil,    83,   250,   142,    50,   nil,    -2,    87,
   nil,    34,   101,   nil,   315,   nil,   nil,   108,   106,    80,
   nil,   nil,   nil,   nil,    96,   nil,   nil,   117,   nil,   nil,
   214,   119,   116,   117,   178,   394,   nil,   nil,   nil,   nil,
   nil,   118,   nil,   139,   nil,   nil,   136,   382,   nil,   nil,
   nil,   123,   144,   134,   nil,   134,   134,    37,   nil,   132,
   nil,   nil,   nil,    -2,   nil,   nil,   nil,   nil,   nil,   146,
   nil,   nil,   118,   nil,   120,   nil,   nil,   157,   154,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   156,   -33,   112,
   nil,   nil,   165,   166,    -7,   nil,   nil,   127,   -28,   -15,
   nil,   106,   nil,   nil,   nil,   nil,   154,   140,   nil,    70,
    33,   nil,   187,   192,    -3,    -1,   178,   216,     9,   nil,
   187,   nil,   223,   225,   nil,   218,   nil,   nil,   nil,   207,
   nil,   nil,    -8,   192,   nil,   nil,   nil,   nil,    37,   195,
   nil,    -7,   nil,   nil ]

racc_action_default = [
    -7,  -173,  -173,   -57,  -173,  -173,   -58,  -173,   -59,   -11,
  -173,  -173,  -173,   -61,    -1,    -7,  -173,   -19,  -173,  -173,
  -173,  -173,   -20,  -173,  -173,  -173,  -138,   -96,   -37,  -139,
   -97,   -90,   -38,  -172,  -101,   -91,   -39,   -28,  -102,   -99,
   -41,   -40,  -103,   -98,  -173,  -100,  -173,   -32,  -107,   -33,
  -108,   -93,   -34,  -109,   -94,   -35,  -168,  -110,   -95,   -36,
  -173,    -6,  -173,  -170,  -171,  -142,  -173,  -173,    -8,    -2,
  -173,    -3,  -173,  -111,   -78,   -66,   -56,  -112,   -81,   -79,
   -74,  -169,  -173,   -82,   -75,  -173,   -83,   -76,   -73,   -67,
   -77,   -80,   -69,  -173,   -70,   -71,   -63,   -72,   -64,  -173,
  -173,   -68,   -65,    -4,   -88,   -60,    -5,   -92,  -173,  -173,
  -105,  -104,  -106,  -173,  -117,  -173,  -173,   -23,  -142,  -173,
  -148,  -173,  -173,  -143,   -18,   254,   -21,  -173,  -173,  -173,
   -88,   -86,   -84,   -87,   -62,   -52,  -137,  -173,   -52,   -29,
  -117,  -173,  -173,  -173,  -114,  -173,   -26,   -24,  -164,  -165,
  -149,  -166,  -150,  -173,  -163,   -12,  -173,    -7,   -17,   -22,
  -136,  -134,  -173,   -42,   -55,   -43,   -45,   -47,   -49,  -173,
   -30,   -31,  -118,  -173,  -140,  -113,  -115,  -123,   -99,  -124,
  -120,  -121,  -173,  -122,  -173,   -10,    -9,  -173,  -173,   -85,
   -52,   -52,   -52,   -52,   -52,   -52,  -116,  -173,  -173,  -144,
  -135,  -133,   -44,   -46,   -48,   -50,   -51,  -173,  -173,  -153,
  -156,  -173,  -157,  -152,  -158,  -145,  -173,  -146,  -167,  -173,
  -128,   -52,  -173,  -173,  -125,  -173,  -173,  -173,  -173,  -147,
  -173,  -141,  -173,  -173,  -129,  -173,  -131,  -119,  -126,  -153,
  -151,  -155,  -160,  -173,  -127,  -132,  -130,  -154,  -173,  -173,
  -162,  -160,  -159,  -161 ]

racc_goto_table = [
    41,    62,    63,    32,    64,    28,   105,    93,    66,     8,
    14,     3,     6,    49,    55,   154,    47,    72,   150,   171,
   189,   104,   117,   169,     8,    68,     3,     6,   161,   134,
   226,   209,   143,   144,   223,   249,   232,   142,   205,   206,
   204,   109,   203,   202,   253,    40,    36,    59,    52,    44,
   238,   182,   159,   234,    76,   158,   188,   153,   239,   199,
   247,   176,   144,   172,   217,   231,   215,   126,   229,   122,
   156,   157,    12,   nil,   nil,   146,   nil,   173,   nil,   128,
   nil,   nil,   129,   207,   nil,   nil,   nil,   nil,   200,   nil,
   130,   245,   nil,   nil,   nil,   nil,   nil,   136,   nil,   nil,
   nil,   nil,   235,   nil,   nil,   154,   nil,   nil,   227,   nil,
   139,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   151,   nil,   nil,   149,   160,   148,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     8,   170,     3,     6,   nil,   130,   nil,
   nil,   nil,   nil,   nil,   179,   nil,   nil,   nil,   nil,   nil,
   184,   nil,   nil,   nil,   177,   nil,   nil,   181,   183,   130,
   180,   nil,   nil,   nil,   nil,   nil,     8,   186,     3,     6,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   160,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   233,   nil,   nil,   nil,   241,
   151,   nil,   nil,   149,   nil,   148,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   104,   nil,   nil,   242,   nil,   nil,
   130,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   251 ]

racc_goto_check = [
    22,    10,    10,    31,    10,    30,    45,    47,    10,    44,
     2,    42,    43,    26,    28,    51,    25,    10,    87,    24,
    58,    10,    19,    40,    44,     2,    42,    43,    77,    48,
    89,    88,    68,    69,    72,    91,    75,    70,    38,    38,
    37,    10,    36,    35,    91,    33,    32,    29,    27,    23,
    72,    71,    18,    74,    41,    17,    78,    80,    88,    81,
    89,    68,    69,    70,    82,    83,    85,    10,    86,    13,
     9,     3,     1,   nil,   nil,    19,   nil,    48,   nil,    10,
   nil,   nil,    10,    40,   nil,   nil,   nil,   nil,    77,   nil,
    10,    58,   nil,   nil,   nil,   nil,   nil,    10,   nil,   nil,
   nil,   nil,    24,   nil,   nil,    51,   nil,   nil,    87,   nil,
    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    22,   nil,   nil,    31,    10,    30,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    44,    10,    42,    43,   nil,    10,   nil,
   nil,   nil,   nil,   nil,    22,   nil,   nil,   nil,   nil,   nil,
    10,   nil,   nil,   nil,    44,   nil,   nil,    26,    28,    10,
    25,   nil,   nil,   nil,   nil,   nil,    44,     2,    42,    43,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    10,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    47,   nil,   nil,   nil,    45,
    22,   nil,   nil,    31,   nil,    30,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    10,   nil,   nil,    22,   nil,   nil,
    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22 ]

racc_goto_pointer = [
   nil,    72,    10,   -53,   nil,   nil,   nil,   nil,   nil,   -54,
    -3,   nil,   nil,     4,   nil,   nil,   nil,   -71,   -74,   -43,
   nil,   nil,    -1,    48,  -119,    15,    12,    47,    13,    46,
     4,     2,    45,    44,   nil,  -147,  -149,  -152,  -155,   nil,
  -112,    33,    11,    12,     9,   -18,   nil,   -14,   -64,   nil,
   nil,  -106,   nil,   nil,   nil,   nil,   nil,   nil,  -142,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   -83,   -82,
   -77,   -94,  -174,   nil,  -167,  -183,   nil,   -99,  -105,   nil,
   -64,  -125,  -135,  -152,   nil,  -133,  -149,  -103,  -167,  -179,
   nil,  -207 ]

racc_goto_default = [
   nil,   nil,   nil,    15,    16,    19,    23,    25,     2,   nil,
    37,     9,    10,   nil,   nil,   nil,    18,   nil,   nil,   nil,
   118,   119,    89,   nil,   164,    92,    94,    95,    97,   101,
    74,    79,   nil,    88,   163,   165,   166,   167,   168,   nil,
   nil,   nil,    78,    83,    86,   131,    13,   141,   nil,    96,
    98,   102,    75,    80,    84,    87,    90,    91,   132,   133,
    51,    54,    58,    27,    30,    34,    38,    42,   nil,   140,
   nil,   nil,   nil,   224,   219,   nil,   220,   nil,   nil,   121,
   nil,   nil,   nil,   nil,   123,   nil,   nil,   nil,   nil,   nil,
   211,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 59, :_reduce_1,
  2, 61, :_reduce_none,
  2, 61, :_reduce_none,
  2, 61, :_reduce_4,
  2, 61, :_reduce_5,
  2, 61, :_reduce_6,
  0, 60, :_reduce_none,
  2, 60, :_reduce_8,
  2, 67, :_reduce_9,
  5, 66, :_reduce_10,
  1, 65, :_reduce_11,
  4, 69, :_reduce_12,
  3, 72, :_reduce_none,
  0, 73, :_reduce_none,
  1, 73, :_reduce_none,
  1, 73, :_reduce_none,
  4, 70, :_reduce_17,
  0, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  0, 75, :_reduce_none,
  1, 75, :_reduce_none,
  1, 71, :_reduce_23,
  2, 78, :_reduce_24,
  0, 77, :_reduce_none,
  2, 77, :_reduce_26,
  0, 76, :_reduce_none,
  1, 80, :_reduce_none,
  3, 80, :_reduce_29,
  4, 80, :_reduce_30,
  5, 63, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 81, :_reduce_none,
  1, 82, :_reduce_none,
  1, 92, :_reduce_none,
  3, 92, :_reduce_none,
  1, 93, :_reduce_none,
  3, 93, :_reduce_none,
  1, 94, :_reduce_none,
  3, 94, :_reduce_none,
  1, 95, :_reduce_none,
  3, 95, :_reduce_none,
  3, 95, :_reduce_none,
  0, 96, :_reduce_none,
  1, 97, :_reduce_none,
  1, 97, :_reduce_none,
  1, 98, :_reduce_none,
  2, 62, :_reduce_none,
  1, 62, :_reduce_none,
  1, 62, :_reduce_none,
  1, 62, :_reduce_none,
  2, 62, :_reduce_none,
  1, 62, :_reduce_none,
  2, 99, :_reduce_none,
  1, 105, :_reduce_none,
  1, 105, :_reduce_none,
  1, 107, :_reduce_none,
  1, 107, :_reduce_none,
  1, 107, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 109, :_reduce_none,
  1, 110, :_reduce_none,
  1, 110, :_reduce_none,
  1, 110, :_reduce_none,
  1, 110, :_reduce_none,
  1, 108, :_reduce_none,
  1, 108, :_reduce_none,
  1, 108, :_reduce_none,
  1, 106, :_reduce_none,
  3, 106, :_reduce_none,
  1, 116, :_reduce_none,
  1, 116, :_reduce_none,
  1, 103, :_reduce_none,
  1, 117, :_reduce_none,
  1, 87, :_reduce_90,
  1, 87, :_reduce_91,
  2, 87, :_reduce_92,
  1, 83, :_reduce_none,
  1, 83, :_reduce_none,
  1, 118, :_reduce_none,
  1, 118, :_reduce_none,
  1, 118, :_reduce_none,
  1, 120, :_reduce_none,
  1, 121, :_reduce_none,
  1, 122, :_reduce_none,
  1, 119, :_reduce_none,
  1, 119, :_reduce_none,
  1, 119, :_reduce_none,
  2, 123, :_reduce_104,
  2, 124, :_reduce_105,
  2, 125, :_reduce_106,
  1, 84, :_reduce_none,
  1, 85, :_reduce_none,
  1, 86, :_reduce_none,
  1, 91, :_reduce_none,
  1, 111, :_reduce_none,
  1, 112, :_reduce_none,
  5, 100, :_reduce_113,
  1, 126, :_reduce_114,
  2, 126, :_reduce_115,
  3, 127, :_reduce_116,
  0, 128, :_reduce_none,
  2, 128, :_reduce_118,
  9, 101, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 129, :_reduce_none,
  1, 130, :_reduce_none,
  2, 130, :_reduce_none,
  3, 131, :_reduce_none,
  1, 132, :_reduce_none,
  2, 132, :_reduce_none,
  3, 134, :_reduce_none,
  2, 134, :_reduce_none,
  2, 133, :_reduce_none,
  6, 102, :_reduce_none,
  0, 136, :_reduce_none,
  2, 136, :_reduce_none,
  1, 135, :_reduce_none,
  2, 114, :_reduce_none,
  1, 88, :_reduce_none,
  1, 89, :_reduce_none,
  5, 64, :_reduce_140,
  6, 79, :_reduce_141,
  0, 137, :_reduce_none,
  1, 137, :_reduce_none,
  0, 140, :_reduce_none,
  1, 140, :_reduce_none,
  0, 141, :_reduce_none,
  1, 141, :_reduce_none,
  1, 142, :_reduce_none,
  1, 138, :_reduce_none,
  1, 138, :_reduce_none,
  4, 139, :_reduce_151,
  2, 139, :_reduce_152,
  0, 147, :_reduce_none,
  3, 147, :_reduce_154,
  3, 146, :_reduce_155,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  1, 148, :_reduce_none,
  5, 143, :_reduce_159,
  0, 149, :_reduce_none,
  3, 149, :_reduce_161,
  3, 144, :_reduce_none,
  1, 145, :_reduce_none,
  1, 145, :_reduce_none,
  1, 145, :_reduce_none,
  1, 145, :_reduce_none,
  6, 115, :_reduce_none,
  1, 90, :_reduce_none,
  1, 113, :_reduce_none,
  2, 104, :_reduce_none,
  2, 104, :_reduce_none,
  1, 68, :_reduce_172 ]

racc_reduce_n = 173

racc_shift_n = 254

racc_token_table = {
  false => 0,
  :error => 1,
  "IDENTIFIER" => 2,
  ";" => 3,
  "module" => 4,
  "{" => 5,
  "}" => 6,
  "interface" => 7,
  "abstract" => 8,
  "local" => 9,
  ":" => 10,
  "const" => 11,
  "=" => 12,
  "|" => 13,
  "^" => 14,
  "&" => 15,
  ">>" => 16,
  "<<" => 17,
  "TRUE" => 18,
  "FALSE" => 19,
  "typedef" => 20,
  "native" => 21,
  "," => 22,
  "float" => 23,
  "double" => 24,
  "long" => 25,
  "short" => 26,
  "longlong" => 27,
  "unsigned" => 28,
  "char" => 29,
  "wchar" => 30,
  "boolean" => 31,
  "octet" => 32,
  "any" => 33,
  "Object" => 34,
  "struct" => 35,
  "union" => 36,
  "switch" => 37,
  "(" => 38,
  ")" => 39,
  "case" => 40,
  "default" => 41,
  "enum" => 42,
  "sequence" => 43,
  "string" => 44,
  "wstring" => 45,
  "exception" => 46,
  "oneway" => 47,
  "void" => 48,
  "in" => 49,
  "out" => 50,
  "inout" => 51,
  "raises" => 52,
  "context" => 53,
  "fixed" => 54,
  "<" => 55,
  ">" => 56,
  "ValueBase" => 57 }

racc_nt_base = 58

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "ID",
  "\";\"",
  "\"module\"",
  "\"{\"",
  "\"}\"",
  "\"interface\"",
  "\"abstract\"",
  "\"local\"",
  "\":\"",
  "\"const\"",
  "\"=\"",
  "\"|\"",
  "\"^\"",
  "\"&\"",
  "\">>\"",
  "\"<<\"",
  "\"TRUE\"",
  "\"FALSE\"",
  "\"typedef\"",
  "\"native\"",
  "\",\"",
  "\"float\"",
  "\"double\"",
  "\"long\"",
  "\"short\"",
  "\"longlong\"",
  "\"unsigned\"",
  "\"char\"",
  "\"wchar\"",
  "\"boolean\"",
  "\"octet\"",
  "\"any\"",
  "\"Object\"",
  "\"struct\"",
  "\"union\"",
  "\"switch\"",
  "\"(\"",
  "\")\"",
  "\"case\"",
  "\"default\"",
  "\"enum\"",
  "\"sequence\"",
  "\"string\"",
  "\"wstring\"",
  "\"exception\"",
  "\"oneway\"",
  "\"void\"",
  "\"in\"",
  "\"out\"",
  "\"inout\"",
  "\"raises\"",
  "\"context\"",
  "\"fixed\"",
  "\"<\"",
  "\">\"",
  "\"ValueBase\"",
  "$start",
  "specification",
  "definition_s",
  "definition",
  "type_dcl",
  "const_dcl",
  "except_dcl",
  "interface",
  "module",
  "definition_p",
  "identifier",
  "interface_dcl",
  "interface_header",
  "interface_body",
  "forward_dcl",
  "forward_dcl_1",
  "interface_header_1",
  "interface_header_2",
  "interface_inheritance_spec",
  "export_s",
  "export",
  "op_dcl",
  "scoped_name",
  "const_type",
  "const_exp",
  "integer_type",
  "char_type",
  "wide_char_type",
  "boolean_type",
  "floating_pt_type",
  "string_type",
  "wide_string_type",
  "fixed_pt_const_type",
  "octet_type",
  "or_expr",
  "xor_expr",
  "and_expr",
  "shift_expr",
  "add_expr",
  "boolean_literal",
  "positive_int_const",
  "type_declarator",
  "struct_type",
  "union_type",
  "enum_type",
  "simple_declarator",
  "constr_forward_decl",
  "type_spec",
  "declarators",
  "simple_type_spec",
  "constr_type_spec",
  "base_type_spec",
  "template_type_spec",
  "any_type",
  "object_type",
  "value_base_type",
  "sequence_type",
  "fixed_pt_type",
  "declarator",
  "complex_declarator",
  "signed_int",
  "unsigned_int",
  "signed_short_int",
  "signed_long_int",
  "signed_longlong_int",
  "unsigned_short_int",
  "unsigned_long_int",
  "unsigned_longlong_int",
  "member_list",
  "member",
  "member_s",
  "switch_type_spec",
  "switch_body",
  "case",
  "case_1",
  "element_spec",
  "case_label",
  "enumerator",
  "enum_type_1",
  "op_dcl_1",
  "op_type_spec",
  "parameter_dcls",
  "op_dcl_2",
  "op_dcl_3",
  "op_attribute",
  "raises_expr",
  "context_expr",
  "param_type_spec",
  "param_dcl",
  "parameter_dcls_1",
  "param_attribute",
  "raises_expr_1" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parse.y', 19)
  def _reduce_1(val, _values, result)
    result=IdlSpecification.new("root")
    val[0].each do |v| result.addChild(v) end if val[0]!=nil

    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'parse.y', 27)
  def _reduce_4(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 28)
  def _reduce_5(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 29)
  def _reduce_6(val, _values, result)
    result = val[0]
    result
  end
.,.,

# reduce 7 omitted

module_eval(<<'.,.,', 'parse.y', 36)
  def _reduce_8(val, _values, result)
      result = Array.new
    result.push(val[0])
    val[1].each do |v| result.push(v) end if val[1]!=nil

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 43)
  def _reduce_9(val, _values, result)
      result = Array.new
    result.push(val[0])
    val[1].each do |v| result.push(v) end if val[1]!=nil

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 50)
  def _reduce_10(val, _values, result)
    result = IdlModule.new(val[1])
    val[3].each do |v| result.addChild(v) end if val[3] != nil

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 56)
  def _reduce_11(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 60)
  def _reduce_12(val, _values, result)
    result = IdlInterface.new(val[0])
    val[2].each do |v| result.addChild(v) end

    result
  end
.,.,

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'parse.y', 71)
  def _reduce_17(val, _values, result)
    result = val[2]
    result
  end
.,.,

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

module_eval(<<'.,.,', 'parse.y', 79)
  def _reduce_23(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 83)
  def _reduce_24(val, _values, result)
    result = val[0]
    result
  end
.,.,

# reduce 25 omitted

module_eval(<<'.,.,', 'parse.y', 87)
  def _reduce_26(val, _values, result)
    result = Array.new
    result.push(val[0])
    val[1].each do |v| result.push(v) end if val[1]!=nil

    result
  end
.,.,

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'parse.y', 98)
  def _reduce_29(val, _values, result)
    result="::"+val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 100)
  def _reduce_30(val, _values, result)
    result=val[0]+"::"+val[3]
    result
  end
.,.,

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

# reduce 89 omitted

module_eval(<<'.,.,', 'parse.y', 170)
  def _reduce_90(val, _values, result)
    p 'float' if @debug
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 171)
  def _reduce_91(val, _values, result)
    p 'double' if @debug
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 172)
  def _reduce_92(val, _values, result)
    p 'long double' if @debug
    result
  end
.,.,

# reduce 93 omitted

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

# reduce 98 omitted

# reduce 99 omitted

# reduce 100 omitted

# reduce 101 omitted

# reduce 102 omitted

# reduce 103 omitted

module_eval(<<'.,.,', 'parse.y', 194)
  def _reduce_104(val, _values, result)
    result = "unsigned short"
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 198)
  def _reduce_105(val, _values, result)
    result = "unsigned long"
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 202)
  def _reduce_106(val, _values, result)
    result = "unsigned longlong"
    result
  end
.,.,

# reduce 107 omitted

# reduce 108 omitted

# reduce 109 omitted

# reduce 110 omitted

# reduce 111 omitted

# reduce 112 omitted

module_eval(<<'.,.,', 'parse.y', 224)
  def _reduce_113(val, _values, result)
    result=IdlStruct.new(val[1])
    val[3].each do |v| result.addChild(v) end if val[3]!=nil

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 230)
  def _reduce_114(val, _values, result)
    result=Array.new
    result.push(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 234)
  def _reduce_115(val, _values, result)
    result=Array.new
    result.push(val[0])
    val[1].each do |v| result.push(v) end if val[1]!=nil

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 241)
  def _reduce_116(val, _values, result)
    result=IdlMember.new(val[1])
    result.setTypeSpec(val[0])

    result
  end
.,.,

# reduce 117 omitted

module_eval(<<'.,.,', 'parse.y', 247)
  def _reduce_118(val, _values, result)
    result=Array.new
    result.push(val[0])
    val[1].each do |v| result.push(v) end if val[1]!=nil

    result
  end
.,.,

# reduce 119 omitted

# reduce 120 omitted

# reduce 121 omitted

# reduce 122 omitted

# reduce 123 omitted

# reduce 124 omitted

# reduce 125 omitted

# reduce 126 omitted

# reduce 127 omitted

# reduce 128 omitted

# reduce 129 omitted

# reduce 130 omitted

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

# reduce 134 omitted

# reduce 135 omitted

# reduce 136 omitted

# reduce 137 omitted

# reduce 138 omitted

# reduce 139 omitted

module_eval(<<'.,.,', 'parse.y', 291)
  def _reduce_140(val, _values, result)
    result = IdlException.new(val[1])
    val[3].each do |v| result.addChild(v) end

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 297)
  def _reduce_141(val, _values, result)
    result = IdlOperation.new(val[2])
   result.setAttribute(val[0])
   result.setTypeSpec(val[1])
   val[3].each do |v| result.addChild(v) end
   result.setRaises(val[4])

    result
  end
.,.,

# reduce 142 omitted

# reduce 143 omitted

# reduce 144 omitted

# reduce 145 omitted

# reduce 146 omitted

# reduce 147 omitted

# reduce 148 omitted

# reduce 149 omitted

# reduce 150 omitted

module_eval(<<'.,.,', 'parse.y', 318)
  def _reduce_151(val, _values, result)
    result = Array.new
    result.push(val[1])
    val[2].each do |v| result.push(v) end if val[2]!=nil

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 323)
  def _reduce_152(val, _values, result)
    result = Array.new
    result
  end
.,.,

# reduce 153 omitted

module_eval(<<'.,.,', 'parse.y', 327)
  def _reduce_154(val, _values, result)
    result = Array.new
    result.push(val[1])
    val[2].each do |v| result.push(v) end if val[2]!=nil

    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 334)
  def _reduce_155(val, _values, result)
    result = IdlParameter.new(val[2])
    result.setTypeSpec(val[1])
    result.setAttribute(val[0])

    result
  end
.,.,

# reduce 156 omitted

# reduce 157 omitted

# reduce 158 omitted

module_eval(<<'.,.,', 'parse.y', 344)
  def _reduce_159(val, _values, result)
    result = Array.new
    result.push(IdlException.new(val[2]))
    val[3].each do |v| result.push(v) end if val[3]!=nil

    result
  end
.,.,

# reduce 160 omitted

module_eval(<<'.,.,', 'parse.y', 350)
  def _reduce_161(val, _values, result)
    result = Array.new
    result.push(IdlException.new(val[1]))
    val[2].each do |v| result.push(v) end if val[2]!=nil

    result
  end
.,.,

# reduce 162 omitted

# reduce 163 omitted

# reduce 164 omitted

# reduce 165 omitted

# reduce 166 omitted

# reduce 167 omitted

# reduce 168 omitted

# reduce 169 omitted

# reduce 170 omitted

# reduce 171 omitted

module_eval(<<'.,.,', 'parse.y', 376)
  def _reduce_172(val, _values, result)
    print 'DEBUG - ID found: ', result, "\n" if @debug
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class IdlParser
