// MOTOR.c
// generated by ORBE Idl Compiler
// InputFile: MOTOR.idl
// @Tue Nov 11 16:28:37 2008

#include        <stdio.h>
#include        <string.h>
#include        "Giop.h"
#include        "Orbe.h"
#include        "MOTOR.h"

void dispatch(Req *req, Reply *reply, Giop_Hdr *header)
{
    u8      *req_ptr;
    u8      *reply_ptr;
    u8      *start;
    CORBA_ushort speed;
    CORBA_boolean result;
    CORBA_ulong __length;
    req_ptr = req->body;
    reply_ptr = start = reply->body;

    if (strcmp((void*) req->operation, "stepRight") == 0) {
	// incoming values
	MOTOR_stepRight(NULL, NULL);

	// return value
	// outgoing values
    }
    if (strcmp((void*) req->operation, "stepLeft") == 0) {
	// incoming values
	MOTOR_stepLeft(NULL, NULL);

	// return value
	// outgoing values
    }
    if (strcmp((void*) req->operation, "startSpin") == 0) {
	// incoming values
	CORBA_octet turnD = *((CORBA_octet*)req_ptr);
	req_ptr += 1;

	speed = *((CORBA_ushort*)req_ptr);
	req_ptr += 2;

	MOTOR_startSpin(NULL, turnD, speed, NULL);

	// return value
	// outgoing values
    }
    if (strcmp((void*) req->operation, "stopSpin") == 0) {
	// incoming values
	MOTOR_stopSpin(NULL, NULL);

	// return value
	// outgoing values
    }
    if (strcmp((void*) req->operation, "getPosition") == 0) {
	// incoming values
	CORBA_octet result = MOTOR_getPosition(NULL, NULL);

	// return value
	memcpy(reply_ptr, (u8*) &result, 1);
	reply_ptr += 1;

	// outgoing values
    }
    if (strcmp((void*) req->operation, "turnOn") == 0) {
	// incoming values
	CORBA_long ID = Orbe_exchangeLong(*(u32*)req_ptr);
	req_ptr += 4;

	MOTOR_turnOn(NULL, ID, NULL);

	// return value
	// outgoing values
    }
    if (strcmp((void*) req->operation, "turnOff") == 0) {
	// incoming values
	CORBA_long ID = Orbe_exchangeLong(*(u32*)req_ptr);
	req_ptr += 4;

	MOTOR_turnOff(NULL, ID, NULL);

	// return value
	// outgoing values
    }
    if (strcmp((void*) req->operation, "getState") == 0) {
	// incoming values
	CORBA_long ID = Orbe_exchangeLong(*(u32*)req_ptr);
	req_ptr += 4;

	result = MOTOR_getState(NULL, ID, NULL);

	// return value
	memcpy(reply_ptr, (u8*) &result, 1);
	reply_ptr += 1;

	// outgoing values
    }
  reply->body_size = (unsigned int) (reply_ptr - start);
}
