// LEDImpl.template.c
// generated by ORBE Idl Compiler
// InputFile: LED.idl
// @Mon Jul 28 16:04:56 2008

#include        "CORBA_Object.h"
#include        "LED.h"
#include 	"xparameters.h"
#include	"xbasic_types.h"
#include	"xio.h"

u32 LED_reg = 0;

void LED_turnOn(
	LED o,
	CORBA_long ID,
	CORBA_Environment* ev)
{
	LED_reg |= 1<<ID;
	XIo_Out32(XPAR_LEDS_8BIT_BASEADDR+0, LED_reg);
}

void LED_turnOff(
	LED o,
	CORBA_long ID,
	CORBA_Environment* ev)
{
	LED_reg &= (0xfffffffe << ID);
	XIo_Out32(XPAR_LEDS_8BIT_BASEADDR+0, LED_reg );
	

}


CORBA_boolean LED_getState(
	LED o,
	CORBA_long ID,
	CORBA_Environment* ev)
{
	return (LED_reg & 1<<ID) != 0;
}
