// LCD.h
// generated by ORBE Idl Compiler
// InputFile: LCD.idl
// @Thu Jul 31 16:39:14 2008

#ifndef _LCD_H

#define _LCD_H

#include        "CORBA_Object.h"
typedef CORBA_Object LCD;

#include        "LCD.h"
extern void LCD_execute(
	LCD o,
	CORBA_octet command,
	CORBA_Environment* ev);
extern void LCD_writeData(
	LCD o,
	CORBA_octet data,
	CORBA_Environment* ev);
extern CORBA_octet LCD_readData(
	LCD o,
	CORBA_Environment* ev);
#endif //_LCD_H
