// LCD.c
// generated by ORBE Idl Compiler
// InputFile: LCD.idl
// @Thu Jul 31 16:39:14 2008

#include        <stdio.h>
#include        <string.h>
#include        "Giop.h"
#include        "Orbe.h"
#include        "LCD.h"


void dispatch(Req *req, Reply *reply, Giop_Hdr *header)
{
    u8      *req_ptr;
    u8      *reply_ptr;
    u8      *start;
    int     tmp = 0;
    CORBA_ulong __length;
    req_ptr = req->body;
    reply_ptr = start = reply->body;

  if (strcmp(req->operation, "execute") == 0) {
          // incoming values
          CORBA_octet command = *((CORBA_octet*)req_ptr);
          req_ptr += 1;

          LCD_execute(NULL, command, NULL);

          // return value
          // outgoing values
  }
  if (strcmp(req->operation, "writeData") == 0) {
          // incoming values
          CORBA_octet data = *((CORBA_octet*)req_ptr);
          req_ptr += 1;

          LCD_writeData(NULL, data, NULL);

          // return value
          // outgoing values
  }
  if (strcmp(req->operation, "readData") == 0) {
          // incoming values
          CORBA_octet result = LCD_readData(NULL, NULL);

          // return value
          memcpy(reply_ptr, (u8*) &result, 1);
          reply_ptr += 1;

          // outgoing values
  }
  reply->body_size = (uint) (reply_ptr - start);
}
